apiVersion: v1
kind: ConfigMap
metadata:
  name: llmobs-config
  namespace: llmobs
data:
  POSTGRES_USER: llmobs
  POSTGRES_DB: llmobs
  REDIS_HOST: redis-svc
  REDIS_PORT: "6379"
  INGESTION_PORT: "4001"
  INGESTION_SERVICE_URL: http://ingestion-svc:4001
  NEXT_PUBLIC_DEFAULT_PROVIDER: google
